### ISSUE TITLE
Final metadata build and push to SB

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/mntoha-data-release#48]
Cannot complete until #47 is closed.

Some things need to be build by different people because of where the data is located. These are all the targets that build and push the XML files.
 
- [x] `scmake("log/00_parent_sb.csv")` # anyone can build this since it is separate from the data
- [x] `scmake("log/01_spatial_sb.csv")`
- [x] `scmake("log/02_observations_sb.csv")`
- [x] `scmake("log/03_configXML_sb.csv")` # anyone can build this since it is separate from the data
- [x] `scmake("log/04_inputs_sb.csv")`
- [x] `scmake("log/05_predictionsPB_sb.csv")`
- [x] `scmake("log/06_evaluationPB_sb.csv")`
- [x] `scmake("log/07_habitat_xml_sb.csv")` # anyone can build this since it is separate from the data

**Comment by lindsayplatt** [comment]
@jread-usgs you might need to build `01` and `02`. Would @hcorson-dosch build `04`, `05`, and `06`?

**Comment by jread-usgs** [comment]
I think I can do all of those :+1:
